
[build.environment]
  TZ="Europe/Zagreb"

[build]
  functions = "src/netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[plugins]]
    package = "netlify-plugin-11ty"
    [plugins.inputs]
        cache_img = './img'
        cache_img_httpHeader = false

        cache_assets = '../.cache'
        cache_other = []

[[plugins]]
package = "netlify-plugin-hashfiles"