[[headers]]
for = "/*"
[headers.values]
Content-Security-Policy = "default-src ‘self’"
[[headers]]
for = "/images/*"
[headers.values]
Cache-Control = "public, max-age=604800, immutable"
[[headers]]
for = "/fonts/*"
[headers.values]
Cache-Control = "public, max-age=604800, immutable"
[[headers]]
for = "/*.pdf"
[headers.values]
Cache-Control = "public, max-age=604800, immutable"
[[headers]]
for = "/*.ico"
[headers.values]
Cache-Control = "public, max-age=604800, immutable"
[[headers]]
for = "/*.flv"
[headers.values]
Cache-Control = "public, max-age=604800, immutable"
[[headers]]
for = "/*.jpg"
[headers.values]
Cache-Control = "public, max-age=604800, immutable"
[[headers]]
for = "/*.jpeg"
[headers.values]
Cache-Control = "public, max-age=604800, immutable"
[[headers]]
for = "/*.webp"
[headers.values]
Cache-Control = "public, max-age=604800, immutable"
[[headers]]
for = "/*.png"
[headers.values]
Cache-Control = "public, max-age=604800, immutable"
[[headers]]
for = "/*.css"
[headers.values]
Cache-Control = "public, max-age=604800, immutable"
[[headers]]
for = "/*.js"
[headers.values]
Cache-Control = "public, max-age=604800, immutable"
[[headers]]
for = "/*sw.js"
[headers.values]
Cache-Control = "public, max-age=604800, immutable"
[[headers]]
for = "/*.html"
[headers.values]
Cache-Control = "public, max-age=0, must-revalidate"

[build.environment]
  TZ="Europe/Zagreb"

[build]
  functions = "functions/"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200