[[headers]]
for = "/*"
[headers.values]
Content-Security-Policy = "Content-Security-Policy: default-src 'none'; script-src 'self'; connect-src 'self'; img-src 'self'; style-src 'self';base-uri 'self';form-action 'self'"
Expect-CT = "max-age=0"
Feature-Policy = "accelerometer ‘none’; camera ‘none’; geolocation ‘none’; gyroscope ‘none’; magnetometer ‘none’; microphone ‘none’; payment ‘none’; usb ‘none’"
Referrer-Policy = "strict-origin-when-cross-origin"
Strict-Transport-Security = "max-age=604800; includeSubDomains; preload"
Vary = "Accept-Encoding"
X-Content-Type-Options = "nosniff"
X-Frame-Options = "*ALLOW-FROM https://www.edukacije.hr*"
X-XSS-Protection = "1; mode=block"
[[headers]]
for = "/images/*"
[headers.values]
Cache-Control = "public, max-age=604800, immutable"
[[headers]]
for = "/fonts/*"
[headers.values]
Cache-Control = "public, max-age=604800, immutable"
[[headers]]
for = "/*.pdf"
[headers.values]
Cache-Control = "public, max-age=604800, immutable"
[[headers]]
for = "/*.ico"
[headers.values]
Cache-Control = "public, max-age=604800, immutable"
[[headers]]
for = "/*.flv"
[headers.values]
Cache-Control = "public, max-age=604800, immutable"
[[headers]]
for = "/*.jpg"
[headers.values]
Cache-Control = "public, max-age=604800, immutable"
[[headers]]
for = "/*.jpeg"
[headers.values]
Cache-Control = "public, max-age=604800, immutable"
[[headers]]
for = "/*.webp"
[headers.values]
Cache-Control = "public, max-age=604800, immutable"
[[headers]]
for = "/*.png"
[headers.values]
Cache-Control = "public, max-age=604800, immutable"
[[headers]]
for = "/*.css"
[headers.values]
Cache-Control = "public, max-age=604800, immutable"
[[headers]]
for = "/*.js"
[headers.values]
Cache-Control = "public, max-age=604800, immutable"
[[headers]]
for = "/*sw.js"
[headers.values]
Cache-Control = "public, max-age=604800, immutable"
[[headers]]
for = "/*.html"
[headers.values]
Cache-Control = "public, max-age=0, must-revalidate"

[build.environment]
  TZ="Europe/Zagreb"

[build]
  functions = "src/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200